name: aktivity_location_app
description: "Modern Activity Location CRM Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.4
  
  # Storage & Networking
  shared_preferences: ^2.5.3
  http: ^1.4.0
  
  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.3.1
  geolocator: ^9.0.2
  permission_handler: ^12.0.1
  google_maps_flutter: ^2.12.3
  geocoding: ^4.0.0
  latlong2: ^0.9.1
  flutter_map: ^8.1.1
  image_picker: ^1.1.2
  file_picker: ^10.2.0
  image: ^4.5.4
  path_provider: ^2.1.5
  package_info_plus: ^8.3.0
  fl_chart: ^0.71.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600